"""The contract every tool in this harness shares.

Each tool returns the same metadata envelope and uses the same exit codes. The
`source` field is the honesty mechanism: it states whether a figure is measured
data, a derived calculation, or the harness's own estimate.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent
CONFIG_DIR = BASE_DIR / "config"
DATA_DIR = BASE_DIR / "data"
MEMORY_DIR = BASE_DIR / "memory"

# --- Exit codes ------------------------------------------------------------
EXIT_OK = 0
EXIT_AUTH = 2          # credentials missing or expired
EXIT_QUOTA = 3         # YouTube API quota exhausted
EXIT_NO_DATA = 4       # not enough data to answer
EXIT_USAGE = 64        # bad arguments (argparse defaults to 2, which would
                       # collide with EXIT_AUTH)

# --- Valid `source` values -------------------------------------------------
SOURCE_API = "youtube_api"      # straight from Google's API
SOURCE_DERIVED = "derived"      # computed in code over API data
SOURCE_HEURISTIC = "heuristic"  # our own rubric or proxy — NOT measured data
SOURCE_CONFIG = "config"        # contents of a local file
SOURCE_GENERATED = "generated"  # artefact from an external model — measures
                                # nothing, and is not evidence of performance

_SOURCES = {SOURCE_API, SOURCE_DERIVED, SOURCE_HEURISTIC, SOURCE_CONFIG,
            SOURCE_GENERATED}

# How the agent must present each kind of figure. This travels inside the
# envelope so the rule sits in front of the model at the moment it cites.
_NOTICE = {
    SOURCE_API: "Straight from the YouTube API.",
    SOURCE_DERIVED: "Computed over API data.",
    SOURCE_HEURISTIC: (
        "OUR OWN ESTIMATE, not measured data. When citing it you must say so "
        "explicitly, and must not present it as a prediction of CTR or views."
    ),
    SOURCE_CONFIG: "Contents of a local config file, not a measurement.",
    SOURCE_GENERATED: (
        "ARTEFACT GENERATED by an external model. Not data and not a "
        "measurement: it says nothing about how it will perform. When "
        "delivering it, name the provider and the model that produced it."
    ),
}


class ToolError(Exception):
    """An err carrying its own exit code from the contract."""

    def __init__(self, message: str, code: int = EXIT_NO_DATA, hint: str = ""):
        super().__init__(message)
        self.message = message
        self.code = code
        self.hint = hint


def envelope(tool: str, source: str, data, params: dict | None = None,
             cache_hit: bool = False, notes: list[str] | None = None) -> dict:
    """Build the standard metadata envelope."""
    if source not in _SOURCES:
        raise ValueError(f"invalid source: {source!r}. Valid: {sorted(_SOURCES)}")
    env = {
        "tool": tool,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "source": source,
        "notice": _NOTICE[source],
        "cache_hit": cache_hit,
        "params": params or {},
        "data": data,
    }
    if notes:
        env["notes"] = notes
    return env


class _Parser(argparse.ArgumentParser):
    """argparse exits with code 2 on a usage error, the same code we use for
    credentials. An agent could not tell "missing token" from "missing
    argument", so usage errors exit with EXIT_USAGE instead.

    The method MUST be called `error`: it overrides argparse's own."""

    def error(self, message):  # noqa: D102
        print(json.dumps({"tool": self.prog, "error": f"bad usage: {message}",
                          "exit_code": EXIT_USAGE}, ensure_ascii=False),
              file=sys.stderr)
        sys.exit(EXIT_USAGE)


def parser(description: str) -> argparse.ArgumentParser:
    """Base parser with the flags every tool shares."""
    p = _Parser(description=description)
    p.add_argument("--json", action="store_true", default=True,
                   help="JSON output (the default)")
    p.add_argument("--md", action="store_true",
                   help="human-readable Markdown output")
    p.add_argument("--no-cache", action="store_true",
                   help="ignore the cache and force an API call")
    return p


def emit(env: dict, args=None, md_fn=None) -> None:
    """Print the result in the requested format and exit with code 0."""
    if args is not None and getattr(args, "md", False) and md_fn is not None:
        print(md_fn(env))
    else:
        print(json.dumps(env, ensure_ascii=False, indent=2, default=str))
    sys.exit(EXIT_OK)


def fail(err: "ToolError | Exception", tool: str = "") -> None:
    """Print a structured err to stderr and exit with its code.

    Never lets a raw traceback escape: the agent needs a message it can read
    and pass on.
    """
    if isinstance(err, ToolError):
        code, message, hint = err.code, err.message, err.hint
    else:
        code, message, hint = EXIT_NO_DATA, str(err), ""
    payload = {"tool": tool, "error": message, "exit_code": code}
    if hint:
        payload["hint"] = hint
    print(json.dumps(payload, ensure_ascii=False, indent=2), file=sys.stderr)
    sys.exit(code)


def main(tool: str, fn) -> None:
    """Execution wrapper: catches errors and translates them to the contract."""
    try:
        fn()
    except ToolError as e:
        fail(e, tool)
    except KeyboardInterrupt:
        sys.exit(130)
    except Exception as e:  # noqa: BLE001 — process boundary, on purpose
        from googleapiclient.errors import HttpError
        if isinstance(e, HttpError):
            if e.resp.status == 403 and "quota" in str(e).lower():
                fail(ToolError(
                    "Daily YouTube API quota exhausted.",
                    EXIT_QUOTA,
                    "The quota resets at midnight Pacific time. Use cached "
                    "data or wait.",
                ), tool)
            fail(ToolError(f"YouTube API err: {e}", EXIT_NO_DATA), tool)
        fail(e, tool)
