#!/usr/bin/env python3
"""Generate an image with the configured provider (fal.ai or an MCP).

Provider-agnostic: the skill asks for an image, not for a model. The format
(`--type`) prepends the technical requirements of wherever the image is going
— the banner's mobile safe zone, the circular crop of a profile picture —
because without them in the prompt the model ignores them.

What comes out carries `source: generated`: an artefact, not a measurement.
It says nothing about how it will perform.
"""
import json
from pathlib import Path

from lib import base  # noqa: F401
from lib import imagegen as ig
from lib.contract import SOURCE_CONFIG, SOURCE_GENERATED, emit, main, parser, envelope

TOOL = "generate_image"


def run():
    p = parser(__doc__)
    p.add_argument("--prompt", required=True, help="what should be in the image")
    p.add_argument("--type", default="thumbnail", dest="kind",
                   choices=list(ig.SPEC), help="where the image is going")
    p.add_argument("--ref", action="append", default=[], metavar="ORIGEN:ROL",
                   help="reference: path, URL or video_id, plus its role "
                        "(likeness|style|composition|packaging). Repeatable, max 3")
    p.add_argument("--model", help="model slug; defaults to the one in the config")
    p.add_argument("--provider", choices=["fal", "mcp"], help="fuerza provider_name")
    p.add_argument("--out", help="output path; defaults to data/images/")
    p.add_argument("--dry-run", action="store_true",
                   help="show the final prompt without spending credits")
    args = p.parse_args()

    cfg = ig.load()
    ig.validate_ratio(cfg, args.kind)
    refs = ig.sort_refs([ig.parse_ref(r, cfg) for r in args.ref], cfg)
    prompt = ig.compose_prompt(args.kind, args.prompt, refs)
    format = cfg["formats"][args.kind]
    provider = ig.provider_name(cfg, args.provider)
    params = {"kind": args.kind, "provider": provider,
              "refs": [f"{r['origin']}:{r['role']}" for r in refs]}

    if provider == "mcp":
        env = envelope(TOOL, SOURCE_CONFIG,
                    ig.mcp_directive(cfg, "generate", prompt, refs, args.kind),
                    params, notes=["This run has NOT generated any image."])
        emit(env, args, lambda e: base.md_header(e) + "\n\n" +
               e["data"]["action_required"] + "\n\n```json\n" +
               json.dumps(e["data"]["call"], ensure_ascii=False, indent=2) +
               "\n```")

    slug = ig.model_slug(cfg, "generate", args.model)

    ig.warn_if_repeated(slug, args.kind, prompt)

    if args.dry_run:
        env = envelope(TOOL, SOURCE_CONFIG, {
            "mode": "dry-run", "model_slug": slug, "format": format,
            "final_prompt": prompt,
            "references": [r["origin"] for r in refs],
        }, params, notes=ig.WARNINGS + [
            "Dry run: fal.ai was not called, there is no cost."])
        emit(env, args, lambda e: base.md_header(e) +
               f"\n\n**Modelo**: `{e['data']['model_slug']}`\n\n**Prompt final**\n\n> " +
               e["data"]["final_prompt"])

    key = ig.fal_key(cfg)
    urls = [ig.reference_url(r["origin"], cfg, key) for r in refs]

    payload = {"prompt": prompt, **ig.size_payload(cfg, args.kind)}
    if urls:
        payload["image_urls"] = urls

    response = ig.enqueue(slug, payload, cfg, key)
    salidas = ig.urls_from(response)
    if not salidas:
        from lib.contract import EXIT_NO_DATA, ToolError
        raise ToolError(f"The model returned no image: {response}",
                        EXIT_NO_DATA)

    dest = Path(args.out) if args.out else ig.output_path(TOOL, args.kind)
    ig.download(salidas[0], dest)

    # The model does not always honour the requested ratio: nano-banana
    # returns 1024x1024 even when asked for 16:9. So the file is measured and,
    # when the format pins a ratio, cropped. "Always 16:9" has to be true in
    # the pixels, not only in the prompt.
    devuelto, corregido = ig.verify_ratio(dest, cfg, args.kind)
    if corregido:
        dest = corregido

    ig.log_generation(TOOL, slug, args.kind, prompt, dest, refs)

    env = envelope(TOOL, SOURCE_GENERATED, {
        "file": str(dest),
        "model_slug": slug,
        "provider_name": "fal.ai",
        "kind": args.kind,
        "target_format": format,
        "final_prompt": prompt,
        "returned_resolution": devuelto,
        "references": [f"{r['origin']} ({r['role']})" for r in refs],
        "extra": salidas[1:],
    }, params, notes=ig.WARNINGS + [
        f"Image generated by {slug} via fal.ai. Name the model when delivering it.",
        "NOT a prediction of anything. To judge it you must open it with vision.",
        f"To set exact dimensions without spending credits: "
        f"python3 tools/export_image.py --image {dest} --type {args.kind}",
    ])
    emit(env, args, lambda e: base.md_header(e) +
           f"\n\n`{e['data']['file']}`\n\nModelo: `{e['data']['model_slug']}`")


if __name__ == "__main__":
    main(TOOL, run)
